name: sdkserver
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  protobuf: ^3.1.0
  protocol:
    path: ../protocol

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
