name: gameserver
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  protobuf: ^3.1.0
  convert: ^3.0.0
  protocol:
    path: ../protocol
  fixnum: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
